	SUBROUTINE SPX_HYABSPAT(CD,EN,NE,FACT)
	INTEGER NE
	REAL CD,EN(NE),FACT(NE)
*CD		input	hydgrogen column 10**21 cm-2
*EN(NE)		input	energies keV
*FACT(NE)	output	absorption factor
*-Author Dick Willingale 1991-Apr-22
	DOUBLE PRECISION WL,HCOL,HEICOL,HEIICOL,RES
C
	HCOL=CD*1.E21
	HEICOL=CD*0.1*1.E21
	HEIICOL=CD*0.001*1.E21
	DO J=1,NE
		WL=12.39854/EN(J)
		CALL ATTEN(WL,HCOL,HEICOL,HEIICOL,RES)
		FACT(J)=RES
	ENDDO
	END
