*+SRT_CHANGEAXES	Do change of axes
	SUBROUTINE SRT_CHANGEAXES(N,X,Y,Z,XA,YA,XD,YD,ZD,ISTAT)
	IMPLICIT NONE
	INTEGER N,ISTAT
	DOUBLE PRECISION X(N),Y(N),Z(N),XA(3),YA(3),XD(N),YD(N),ZD(N)
*-Author Dick Willingale 2002-Feb-27
	DOUBLE PRECISION V(3),ZA(3)
	INTEGER J
C
	IF(ISTAT.NE.0) RETURN
C Normalise X and Y axes
	CALL SRT_VNRM(XA,ISTAT)
	CALL SRT_VNRM(YA,ISTAT)
	IF(ISTAT.NE.0) RETURN
C Find Z axis
	CALL SRT_VCRS(XA,YA,ZA)
C
	DO J=1,N
		V(1)=X(J)
		V(2)=Y(J)
		V(3)=Z(J)
		CALL SRT_VDOT(V,XA,XD(J))
		CALL SRT_VDOT(V,YA,YD(J))
		CALL SRT_VDOT(V,ZA,ZD(J))
	ENDDO
	END
