*+SRT_SCRN	Generate sceening device array from coefficients
	SUBROUTINE SRT_SCRN(NX,X,NA,A,NC,C,R,ISTAT)
	IMPLICIT NONE
	INTEGER NX,NA,NC,ISTAT
	DOUBLE PRECISION X(NX),A(NA),C(NC)
	DOUBLE PRECISION R(NX,NA)
*-Author Dick Willingale 1996-May-1996
	DOUBLE PRECISION SRT_FLEG
	EXTERNAL SRT_FLEG
	INTEGER J,K
C
	IF(ISTAT.NE.0) RETURN
C
	IF(NC.NE.21) THEN
		WRITE(*,*) 'SCREEN error - wrong number of coefficients'
		ISTAT=1
		RETURN
	ENDIF
C
	DO J=1,NA
		DO K=1,NX
			R(K,J)=SRT_FLEG(X(K),A(J),C,3,7,ISTAT)
		ENDDO
	ENDDO
	END
