*+SRT_ACOS	Arccos of complex
	FUNCTION SRT_ACOS(X)
	IMPLICIT NONE
	COMPLEX X,SRT_ACOS
*-Author Dick Willingale 1997-Feb-28
	COMPLEX X2
C
	X2=SQRT(X**2-1.0)
	X2=X+X2
	IF(ABS(X2).NE.0.0) THEN
		SRT_ACOS=CMPLX(0.0,-1.0)*LOG(X2)
	ELSE
		SRT_ACOS=CMPLX(0.0,0.0)
	ENDIF
	END
