*+SRT_BFIELD	Do calculation for BFIELD
	SUBROUTINE SRT_BFIELD(NPOLE,DM,PPOLE,DPOLE,NPOS,POS,BF,ISTAT)
	INTEGER NPOLE,NPOS,ISTAT
	DOUBLE PRECISION DM(NPOLE),PPOLE(3,NPOLE),DPOLE(3,NPOLE)
	DOUBLE PRECISION POS(3,NPOS),BF(3,NPOS)
*-Author Dick Willingale 1994-Sep-16
	DOUBLE PRECISION B(3),R
C
	IF(ISTAT.NE.0) RETURN
C
	DO J=1,NPOS
		BF(1,J)=0.0
		BF(2,J)=0.0
		BF(3,J)=0.0
		DO I=1,NPOLE
			CALL SRT_BDIPOLE(DM(I),PPOLE(1,I),DPOLE(1,I),
     +			POS(1,J),B,R,ISTAT)
			BF(1,J)=BF(1,J)+B(1)
			BF(2,J)=BF(2,J)+B(2)
			BF(3,J)=BF(3,J)+B(3)
		ENDDO
	ENDDO
	END
