*+SYS_DRAND	return a random number in range 0 to 1
	FUNCTION SYS_DRAND()
	DOUBLE PRECISION SYS_DRAND
*Note seed is set by SYS_SRAND(iseed)
*-Author Dick Willingale 1996_Jan_23
	INTEGER IDUM
	COMMON/RSEED/IDUM
	DOUBLE PRECISION SYS_DRAN0
	EXTERNAL SYS_DRAN0
	SYS_DRAND=SYS_DRAN0(IDUM)
	END
